print("****************")
print("Tugas D-1 Kelas B")
print("****************")
print("Nama	: Fernando Hadi W")
print("NPM	: 21083010080")
print("****************")
print("Notes	:")
print("Halo DUnia")
print("Ini adalah skrip Bash pertamaku di Linux!")
